Repository vegaprotocol/data-node, pull requests merged in 2022-07, with the labels that each got.

#765 chore: remove check for API v2
  api/server.go
  api/trading_data_v2.go
Labels: no-changelog

#767 feat: use debian image for data-node docker image
  docker/Dockerfile
Labels: no-changelog

#775 chore: add postgres instructions to readme
  .spelling
  README.md
Labels: no-changelog

#766 fix: allow node added to be updated when loading from a checkpoint
  sqlstore/migrations/0001_initial.sql
  sqlstore/node.go
  sqlstore/node_test.go
  sqlsubscribers/node.go
Labels: no-changelog

#798 chore: remove count from pagination entities
  api/trading_data_v2.go
  gateway/graphql/generated.go
  gateway/graphql/models.go
  gateway/graphql/resolvers.go
  gateway/graphql/schema.graphql
Labels: no-changelog

#804 fix: incorrect reopening of issues
  .github/workflows/project_management.yml
Labels: no-changelog, no-issue

#812 chore: update timescale version in read me
  README.md
Labels: no-changelog

#818 fix: return proposal rationale
  CHANGELOG.md
  entities/proposal.go
Labels: bug

#822 fix: don't skip check when review is dismissed
  .github/workflows/project_management.yml
Labels: no-changelog, no-issue

#825 ci: add develop release action
  Jenkinsfile
Labels: no-changelog, no-issue

#830 fix: marginsConnection was returning error
  api/trading_data_v2.go
Labels: 🧮 DatanodeV2, no-changelog, no-issue

#773 chore: use alpine base image
  docker/Dockerfile
Labels: no-changelog, no-issue

#838 Feature/set asset limits
  api/trading_data.go
  api/trading_data_v2.go
  entities/enums.go
  entities/market.go
  gateway/graphql/generated.go
  gateway/graphql/marshallers/account_type.go
  gateway/graphql/mocks/trading_data_service_client_v2_mock.go
  gateway/graphql/modelext.go
  gateway/graphql/models.go
  gateway/graphql/resolvers.go
  gateway/graphql/schema.graphql
  go.mod
  go.sum
  sqlstore/markets_test.go
  sqlstore/migrations/0001_initial.sql
  sqlsubscribers/market_created_test.go
Labels: no-changelog

#844 fix: ignore errors during s3 development
  Jenkinsfile
Labels: no-changelog, no-issue

#837 chore: update protos + vega core
  entities/id.go
  entities/market.go
  entities/transfer.go
  gateway/graphql/marshallers/account_type.go
  gateway/graphql/transfers_resolver.go
  go.mod
  go.sum
  sqlstore/accounts.go
  sqlstore/transfers_test.go
Labels: no-changelog, no-issue
